### ISSUE TITLE
No banner for admin

### ISSUE THREAD

**Issue by viktorix** [azurecurve/azrcrv-maintenance-mode#1]
Hey, quick suggestion. It would be nice if the admin banner was disabled when both the header/message fields are empty. Right now it shows a red banner without text if those fields are empty. Thanks.

**Comment by azurecurve** [comment]
Sounds reasonable; I'll take a look at adding this.

**Comment by azurecurve** [comment]
[v1.4.0](https://github.com/azurecurve/azrcrv-maintenance-mode/releases/tag/v1.4.0) has been released with this request included.

Empty fields aren't output, but there is also a toggle to disable the admin banner.
